apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: api-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: TTS_SERVICE_ADDR
              value: "tts-service:50051"
